In [107]:
from PIL import Image
import pandas as pd

In [120]:
img = pd.read_csv('G_6.csv', header = None)
img = img.drop(columns = 1000)
display(img.head(),)
img = img.to_numpy()

0    1    2    3    4    5    6    7    8    9    ...  990  991  992  993  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   994  995  996  997  998  999  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 1000 columns]

In [121]:

print(img)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [122]:
img = img * 255
im = Image.fromarray(img)
im = im.convert('L')  # 这样才能转为灰度图，如果是彩色图则改L为‘RGB’
im.save('outfile.png')